# This file is generated by hacks/docker-flake-metadata.sh
# DO NOT EDIT THIS FILE MANUALLY

variable "DOCKER_FLAKE_METADATA_IMAGES" {
	default = ""
	type = string
}
variable "_images" {
	type = list(string)
	default = split(",", replace(DOCKER_FLAKE_METADATA_IMAGES, "\n", ","))
}

function "tags" {
	params = [ name, tag ]
	result = [for image in _images : "${image != "" ? "${image}/" : ""}${name}:${tag}"]
}
